{{- range .Values.ingresses }}
---
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .app }}
  namespace: {{ $.Values.namespace }}
  {{- with $.Values.ingress_labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $.Values.ingress_annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .rules }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ .service }}
              servicePort: {{ .port }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
