{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }} 
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations: {{- include "chart-template.gitlabAnnotations" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
  {{- range .ports }}
    - name: {{ .app }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
  {{- end }}
  {{- with .labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
